apiVersion: v1
kind: Service
metadata:
  name: otus-hw02-service
spec:
  selector:
    app: otus-hw02-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 8000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.db.name }}
spec:
  selector:
    app: {{ .Values.deployment.db.name }}
  ports:
    - port: {{ .Values.service.db.port }}
  type: {{ .Values.service.db.type }}
