server:
  servlet:
    context-path: /
  port: 8000

management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: archHomework
  main:
    banner-mode: off

logging:
  level:
    root: INFO
    org.springframework: INFO
    ru.gur.arch: INFO
